# Generated by Django 4.2.4 on 2023-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_rename_blog_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("tech", models.TextField()),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
            ],
        ),
    ]
