# Generated by Django 4.2.5 on 2023-09-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_post_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(default='#fff', max_length=20, unique=True),
        ),
    ]
